#include "pm_image_cmd_includes.hpp"
#include "pm_image_cmd_info.hpp"

#include "core/settings_store.hpp"
#include "pm_image_register_cli.hpp"

#if defined(FEATURE_XBLOX) && FEATURE_XBLOX && defined(FEATURE_COMMAND_XBLOX) && FEATURE_COMMAND_XBLOX
#include "xblox/blocks/builtin_blocks.hpp"
#endif

#include <filesystem>
#include <fstream>
#include <sstream>

namespace {

namespace fs = std::filesystem;

std::string read_text_file(const fs::path& path)
{
    std::ifstream ifs(path, std::ios::binary);
    if (!ifs)
        return {};
    std::ostringstream ss;
    ss << ifs.rdbuf();
    return ss.str();
}

bool write_text_file(const fs::path& path, const std::string& text, std::string& err)
{
    std::error_code ec;
    fs::create_directories(path.parent_path(), ec);
    if (ec) {
        err = "create directories failed: " + ec.message();
        return false;
    }
    std::ofstream ofs(path, std::ios::binary | std::ios::trunc);
    if (!ofs) {
        err = "cannot write " + path.string();
        return false;
    }
    ofs << text;
    return true;
}

std::string md_escape_cell(std::string s)
{
    for (char& c : s) {
        if (c == '\n' || c == '\r')
            c = ' ';
        if (c == '|')
            c = '/';
    }
    return s;
}

std::string option_primary_name(const CLI::Option* opt)
{
    if (!opt)
        return {};
    return opt->get_name(opt->get_positional(), true);
}

void append_cli_app(std::ostringstream& os, CLI::App* cmd, const std::string& path, int depth)
{
    if (!cmd || path.empty())
        return;
    const int heading = depth <= 0 ? 3 : 4;
    os << std::string(static_cast<std::size_t>(heading), '#') << " `" << path << "`\n\n";
    if (!cmd->get_description().empty())
        os << cmd->get_description() << "\n\n";

    const auto options = cmd->get_options();
    bool wrote_options = false;
    for (const auto* opt : options) {
        if (!opt)
            continue;
        const std::string name = option_primary_name(opt);
        if (name == "-h,--help" || name == "--help" || name == "-h" || name == "--json")
            continue;
        if (!wrote_options) {
            os << "Options:\n";
            wrote_options = true;
        }
        os << "- `" << name << "`";
        std::string bits;
        if (!opt->get_type_name().empty())
            bits += opt->get_type_name();
        if (opt->get_required())
            bits += bits.empty() ? "required" : ", required";
        if (!opt->get_default_str().empty())
            bits += (bits.empty() ? "default `" : ", default `") + opt->get_default_str() + "`";
        if (!bits.empty())
            os << " (" << bits << ")";
        if (!opt->get_description().empty())
            os << " - " << opt->get_description();
        os << "\n";
    }
    if (wrote_options)
        os << "\n";

    for (auto* child : cmd->get_subcommands({})) {
        if (!child || child->get_name().empty())
            continue;
        append_cli_app(os, child, path + " " + child->get_name(), depth + 1);
    }
}

CLI::App* find_child_command(CLI::App& app, const std::string& name)
{
    for (auto* child : app.get_subcommands({})) {
        if (child && child->get_name() == name)
            return child;
    }
    return nullptr;
}

fs::path default_skill_path(const char* name)
{
    return media::settings::get_config_dir() / "skills" / name / "SKILL.md";
}

std::string generated_marker()
{
    return "<!-- Generated by `pm-image-cli info ...`. Edit `skill.in.md` next to this file to prepend local guidance. -->\n\n";
}

std::string compose_skill(const fs::path& dst,
                          const std::string& default_frontmatter,
                          const std::string& generated_body)
{
    const fs::path skill_in = dst.parent_path() / "skill.in.md";
    const std::string prefix = read_text_file(skill_in);
    if (!prefix.empty()) {
        std::string out = prefix;
        if (out.back() != '\n')
            out.push_back('\n');
        out += "\n";
        out += generated_marker();
        out += generated_body;
        return out;
    }
    return default_frontmatter + "\n" + generated_marker() + generated_body;
}

fs::path selected_dst(const PmImageCliState& st, const char* skill_name)
{
    if (!st.info_dst.empty())
        return fs::path(st.info_dst);
    return default_skill_path(skill_name);
}

int emit_skill(const PmImageCliState& st,
               const fs::path& dst,
               const std::string& content)
{
    if (st.info_stdout) {
        std::cout << content;
        if (content.empty() || content.back() != '\n')
            std::cout << "\n";
        return 0;
    }
    std::string err;
    if (!write_text_file(dst, content, err)) {
        std::cerr << "info: " << err << "\n";
        return 1;
    }
    std::cout << "Wrote " << dst.string() << "\n";
    return 0;
}

std::string commands_skill_body(CLI::App& app)
{
    std::ostringstream os;
    os << "# PM-Image Commands\n\n";
    os << "Use this skill when composing PM-Image CLI invocations or calling user custom commands.\n\n";
    os << "## Invocation Rules\n\n";
    os << "- Prefer `pm-image-cli.exe <command> ...` for shell automation and stdout/stderr output.\n";
    os << "- `pm-image.exe <command> ...` accepts the same CLI surface, but is the Windows app executable; use the CLI exe when an agent needs command output.\n";
    os << "- Built-in commands are top-level tokens, for example `pm-image-cli.exe resize --src in.png --dst out.png`.\n";
    os << "- Custom commands are also top-level CLI subcommands, but their IDs must be exact. Use `pm-image-cli.exe custom.mic-start`, not `mic-start`, `custom mic-start`, or `custom_mic_start`.\n";
    os << "- If appending extra args to a custom command, use `--` before args that should not be consumed by the wrapper.\n\n";

    os << "## Built-In CLI Commands\n\n";
    for (const auto& c : pm::cli::registered_cli_commands()) {
        if (!c.available)
            continue;
        const std::string id = c.id ? c.id : "";
        if (id.empty())
            continue;
        if (auto* sub = find_child_command(app, id)) {
            append_cli_app(os, sub, id, 0);
        } else {
            os << "### `" << id << "`\n\n";
            if (c.label && c.label[0])
                os << c.label << ".\n\n";
        }
    }

    const auto custom = pm::cli::visible_custom_commands();
    os << "## Custom Commands\n\n";
    if (custom.empty()) {
        os << "_No enabled/visible custom commands found in commands.json._\n";
    } else {
        os << "| Exact ID | Label | Group | Action |\n";
        os << "|:---|:---|:---|:---|\n";
        for (const auto& c : custom) {
            os << "| `" << md_escape_cell(c.id) << "` | "
               << md_escape_cell(c.label) << " | "
               << md_escape_cell(c.group) << " | `"
               << md_escape_cell(c.action) << "` |\n";
        }
        os << "\nCall custom commands with the exact dotted ID shown above. Example: `pm-image-cli.exe custom.mic-start`.\n";
    }
    return os.str();
}

std::string commands_skill(CLI::App& app, const fs::path& dst)
{
    const std::string frontmatter =
        "---\n"
        "name: pm-image-commands\n"
        "description: PM-Image CLI and custom command reference. Use when composing pm-image.exe/pm-image-cli.exe invocations or calling commands.json presets.\n"
        "---\n";
    return compose_skill(dst, frontmatter, commands_skill_body(app));
}

#if defined(FEATURE_XBLOX) && FEATURE_XBLOX && defined(FEATURE_COMMAND_XBLOX) && FEATURE_COMMAND_XBLOX
std::string json_compact(const nlohmann::json& j)
{
    return j.dump();
}

std::string xblox_skill_body()
{
    std::ostringstream os;
    os << "# PM-Image XBlox\n\n";
    os << "Use this skill when composing `.xblox` block-tree command flows.\n\n";
    os << "## Invocation Rules\n\n";
    os << "- Run flows with `pm-image-cli.exe xblox run --src flow.xblox`.\n";
    os << "- `pm-image.exe xblox run --src flow.xblox` accepts the same command, but prefer `pm-image-cli.exe` when an agent needs stdout/stderr output.\n";
    os << "- Inspect machine-readable block metadata with `pm-image-cli.exe xblox info --json`.\n";
    os << "- XBlox command blocks that call custom commands must use exact IDs, for example `custom.mic-start`, not `mic-start`.\n\n";
    os << "## Document Shape\n\n";
    os << "`{ \"version\": 1, \"context\": {}, \"roots\": [...] }`\n\n";
    os << "## Calling Commands From XBlox\n\n";
    os << "Use a command block with an exact custom command ID:\n\n";
    os << "```json\n";
    os << "{ \"kind\": \"command\", \"command\": { \"id\": \"custom.mic-start\" } }\n";
    os << "```\n\n";
    os << "Inline CLI command payloads are also supported:\n\n";
    os << "```json\n";
    os << "{ \"kind\": \"command\", \"command\": { \"cliCommand\": \"audio\", \"args\": [\"record\", \"status\"] } }\n";
    os << "```\n\n";

    os << "## Blocks\n\n";
    std::string current_group;
    for (const auto& block : media::xblox::blocks::registered_block_definitions()) {
        const std::string group = block.group.empty() ? "Other" : block.group;
        if (group != current_group) {
            current_group = group;
            os << "### " << current_group << "\n\n";
        }
        os << "#### `" << block.kind << "`";
        if (!block.label.empty() && block.label != block.kind)
            os << " - " << block.label;
        os << "\n\n";
        if (!block.description.empty())
            os << block.description << "\n\n";
        if (block.params.is_array() && !block.params.empty()) {
            os << "Params:\n";
            for (const auto& p : block.params) {
                if (!p.is_object())
                    continue;
                os << "- `" << p.value("name", std::string{}) << "` ("
                   << p.value("type", std::string{"value"});
                if (p.value("required", false))
                    os << ", required";
                if (p.contains("default"))
                    os << ", default `" << json_compact(p["default"]) << "`";
                os << ")\n";
            }
            os << "\n";
        }
        os << "Default block: `" << json_compact(block.default_block) << "`\n\n";
    }

    const auto custom = pm::cli::visible_custom_commands();
    os << "## Supported Custom Commands\n\n";
    if (custom.empty()) {
        os << "_No enabled/visible custom commands found in commands.json._\n";
    } else {
        os << "| Exact ID | Label | Action |\n|:---|:---|:---|\n";
        for (const auto& c : custom) {
            os << "| `" << md_escape_cell(c.id) << "` | "
               << md_escape_cell(c.label) << " | `"
               << md_escape_cell(c.action) << "` |\n";
        }
    }
    return os.str();
}
#else
std::string xblox_skill_body()
{
    return "# PM-Image XBlox\n\nXBlox is not enabled in this build.\n";
}
#endif

std::string xblox_skill(const fs::path& dst)
{
    const std::string frontmatter =
        "---\n"
        "name: pm-image-xblox\n"
        "description: PM-Image XBlox block-flow reference. Use when composing .xblox documents, block params, or command blocks.\n"
        "---\n";
    return compose_skill(dst, frontmatter, xblox_skill_body());
}

} // namespace

int pm_image_cmd_info(CLI::App& app, PmImageCliState& st)
{
    if (st.info_commands_cmd && st.info_commands_cmd->parsed()) {
        const fs::path dst = selected_dst(st, "commands");
        return emit_skill(st, dst, commands_skill(app, dst));
    }
    if (st.info_xblox_cmd && st.info_xblox_cmd->parsed()) {
        const fs::path dst = selected_dst(st, "xblox");
        return emit_skill(st, dst, xblox_skill(dst));
    }
    return 0;
}

void pm_image_register_info(CLI::App& app, PmImageCliState& s)
{
    s.info_cmd = app.add_subcommand(
        "info",
        "Generate agent skill references for PM-Image commands and XBlox.");
    s.info_cmd->require_subcommand(1);

    s.info_commands_cmd = s.info_cmd->add_subcommand(
        "commands",
        "Write a PM-Image CLI/custom command skill (default: profile skills/commands/SKILL.md).");
    s.info_commands_cmd->add_option(
        "--dst", s.info_dst,
        "Destination SKILL.md path. Default: <profile>/skills/commands/SKILL.md.");
    s.info_commands_cmd->add_flag(
        "--stdout", s.info_stdout,
        "Print generated skill markdown instead of writing --dst.");

    s.info_xblox_cmd = s.info_cmd->add_subcommand(
        "xblox",
        "Write an XBlox block-flow skill (default: profile skills/xblox/SKILL.md).");
    s.info_xblox_cmd->add_option(
        "--dst", s.info_dst,
        "Destination SKILL.md path. Default: <profile>/skills/xblox/SKILL.md.");
    s.info_xblox_cmd->add_flag(
        "--stdout", s.info_stdout,
        "Print generated skill markdown instead of writing --dst.");
}
