// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: parameter.proto
// Protobuf C++ Version: 6.34.0-dev

#ifndef parameter_2eproto_2epb_2eh
#define parameter_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6034000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_parameter_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_parameter_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_parameter_2eproto;
}  // extern "C"
namespace nodehub {
class ParameterValue;
struct ParameterValueDefaultTypeInternal;
extern ParameterValueDefaultTypeInternal _ParameterValue_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ParameterValue_class_data_;
}  // namespace nodehub
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace nodehub {

// ===================================================================


// -------------------------------------------------------------------

class ParameterValue final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:nodehub.ParameterValue) */ {
 public:
  inline ParameterValue() : ParameterValue(nullptr) {}
  ~ParameterValue() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ParameterValue* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ParameterValue));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ParameterValue(::google::protobuf::internal::ConstantInitialized);

  inline ParameterValue(const ParameterValue& from) : ParameterValue(nullptr, from) {}
  inline ParameterValue(ParameterValue&& from) noexcept
      : ParameterValue(nullptr, ::std::move(from)) {}
  inline ParameterValue& operator=(const ParameterValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline ParameterValue& operator=(ParameterValue&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ParameterValue& default_instance() {
    return *reinterpret_cast<const ParameterValue*>(
        &_ParameterValue_default_instance_);
  }
  enum ValueCase {
    kIntVal = 1,
    kFloatVal = 2,
    kBoolVal = 3,
    kStringVal = 4,
    VALUE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ParameterValue& a, ParameterValue& b) { a.Swap(&b); }
  inline void Swap(ParameterValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ParameterValue* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ParameterValue* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ParameterValue>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ParameterValue& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ParameterValue& from) { ParameterValue::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ParameterValue* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "nodehub.ParameterValue"; }

  explicit ParameterValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ParameterValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ParameterValue& from);
  ParameterValue(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ParameterValue&& from) noexcept
      : ParameterValue(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIntValFieldNumber = 1,
    kFloatValFieldNumber = 2,
    kBoolValFieldNumber = 3,
    kStringValFieldNumber = 4,
  };
  // int32 int_val = 1;
  [[nodiscard]] bool has_int_val()
      const;
  void clear_int_val() ;
  ::int32_t int_val() const;
  void set_int_val(::int32_t value);

  private:
  ::int32_t _internal_int_val() const;
  void _internal_set_int_val(::int32_t value);

  public:
  // float float_val = 2;
  [[nodiscard]] bool has_float_val()
      const;
  void clear_float_val() ;
  float float_val() const;
  void set_float_val(float value);

  private:
  float _internal_float_val() const;
  void _internal_set_float_val(float value);

  public:
  // bool bool_val = 3;
  [[nodiscard]] bool has_bool_val()
      const;
  void clear_bool_val() ;
  bool bool_val() const;
  void set_bool_val(bool value);

  private:
  bool _internal_bool_val() const;
  void _internal_set_bool_val(bool value);

  public:
  // string string_val = 4;
  [[nodiscard]] bool has_string_val()
      const;
  void clear_string_val() ;
  const ::std::string& string_val() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_string_val(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_string_val();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_string_val();
  void set_allocated_string_val(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_string_val() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_string_val(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_string_val();

  public:
  void clear_value();
  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:nodehub.ParameterValue)
 private:
  class _Internal;
  void set_has_int_val();
  void set_has_float_val();
  void set_has_bool_val();
  void set_has_string_val();
  [[nodiscard]] inline bool has_value() const;
  inline void clear_has_value();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 4,
                                   0, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ParameterValue& from_msg);
    union ValueUnion {
      constexpr ValueUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::int32_t int_val_;
      float float_val_;
      bool bool_val_;
      ::google::protobuf::internal::ArenaStringPtr string_val_;
    } value_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_parameter_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ParameterValue_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ParameterValue

// int32 int_val = 1;
inline bool ParameterValue::has_int_val() const {
  return value_case() == kIntVal;
}
inline void ParameterValue::set_has_int_val() {
  _impl_._oneof_case_[0] = kIntVal;
}
inline void ParameterValue::clear_int_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kIntVal) {
    _impl_.value_.int_val_ = 0;
    clear_has_value();
  }
}
inline ::int32_t ParameterValue::int_val() const {
  // @@protoc_insertion_point(field_get:nodehub.ParameterValue.int_val)
  return _internal_int_val();
}
inline void ParameterValue::set_int_val(::int32_t value) {
  if (value_case() != kIntVal) {
    clear_value();
    set_has_int_val();
  }
  _impl_.value_.int_val_ = value;
  // @@protoc_insertion_point(field_set:nodehub.ParameterValue.int_val)
}
inline ::int32_t ParameterValue::_internal_int_val() const {
  if (value_case() == kIntVal) {
    return _impl_.value_.int_val_;
  }
  return 0;
}

// float float_val = 2;
inline bool ParameterValue::has_float_val() const {
  return value_case() == kFloatVal;
}
inline void ParameterValue::set_has_float_val() {
  _impl_._oneof_case_[0] = kFloatVal;
}
inline void ParameterValue::clear_float_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kFloatVal) {
    _impl_.value_.float_val_ = 0;
    clear_has_value();
  }
}
inline float ParameterValue::float_val() const {
  // @@protoc_insertion_point(field_get:nodehub.ParameterValue.float_val)
  return _internal_float_val();
}
inline void ParameterValue::set_float_val(float value) {
  if (value_case() != kFloatVal) {
    clear_value();
    set_has_float_val();
  }
  _impl_.value_.float_val_ = value;
  // @@protoc_insertion_point(field_set:nodehub.ParameterValue.float_val)
}
inline float ParameterValue::_internal_float_val() const {
  if (value_case() == kFloatVal) {
    return _impl_.value_.float_val_;
  }
  return 0;
}

// bool bool_val = 3;
inline bool ParameterValue::has_bool_val() const {
  return value_case() == kBoolVal;
}
inline void ParameterValue::set_has_bool_val() {
  _impl_._oneof_case_[0] = kBoolVal;
}
inline void ParameterValue::clear_bool_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kBoolVal) {
    _impl_.value_.bool_val_ = false;
    clear_has_value();
  }
}
inline bool ParameterValue::bool_val() const {
  // @@protoc_insertion_point(field_get:nodehub.ParameterValue.bool_val)
  return _internal_bool_val();
}
inline void ParameterValue::set_bool_val(bool value) {
  if (value_case() != kBoolVal) {
    clear_value();
    set_has_bool_val();
  }
  _impl_.value_.bool_val_ = value;
  // @@protoc_insertion_point(field_set:nodehub.ParameterValue.bool_val)
}
inline bool ParameterValue::_internal_bool_val() const {
  if (value_case() == kBoolVal) {
    return _impl_.value_.bool_val_;
  }
  return false;
}

// string string_val = 4;
inline bool ParameterValue::has_string_val() const {
  return value_case() == kStringVal;
}
inline void ParameterValue::set_has_string_val() {
  _impl_._oneof_case_[0] = kStringVal;
}
inline void ParameterValue::clear_string_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() == kStringVal) {
    _impl_.value_.string_val_.Destroy();
    clear_has_value();
  }
}
inline const ::std::string& ParameterValue::string_val() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:nodehub.ParameterValue.string_val)
  return _internal_string_val();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ParameterValue::set_string_val(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value_case() != kStringVal) {
    clear_value();

    set_has_string_val();
    _impl_.value_.string_val_.InitDefault();
  }
  _impl_.value_.string_val_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:nodehub.ParameterValue.string_val)
}
inline ::std::string* PROTOBUF_NONNULL ParameterValue::mutable_string_val()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  if (value_case() != kStringVal) {
    clear_value();

    set_has_string_val();
    _impl_.value_.string_val_.InitDefault();
  }
  ::std::string* _s = _internal_mutable_string_val();
  // @@protoc_insertion_point(field_mutable:nodehub.ParameterValue.string_val)
  return _s;
}
inline const ::std::string& ParameterValue::_internal_string_val() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (value_case() != kStringVal) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.value_.string_val_.Get();
}
inline void ParameterValue::_internal_set_string_val(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.string_val_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ParameterValue::_internal_mutable_string_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.string_val_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ParameterValue::release_string_val() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:nodehub.ParameterValue.string_val)
  if (value_case() != kStringVal) {
    return nullptr;
  }
  clear_has_value();
  return _impl_.value_.string_val_.Release();
}
inline void ParameterValue::set_allocated_string_val(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_value()) {
    clear_value();
  }
  if (value != nullptr) {
    set_has_string_val();
    _impl_.value_.string_val_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:nodehub.ParameterValue.string_val)
}

inline bool ParameterValue::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void ParameterValue::clear_has_value() {
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}
inline ParameterValue::ValueCase ParameterValue::value_case() const {
  return ParameterValue::ValueCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace nodehub


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // parameter_2eproto_2epb_2eh
