// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: parameter.proto
// Protobuf C++ Version: 6.34.0-dev

#include "parameter.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace nodehub {

inline constexpr ParameterValue::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR ParameterValue::ParameterValue(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ParameterValue_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ParameterValueDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ParameterValueDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ParameterValueDefaultTypeInternal() {}
  union {
    ParameterValue _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ParameterValueDefaultTypeInternal _ParameterValue_default_instance_;
}  // namespace nodehub
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_parameter_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_parameter_2eproto = nullptr;
const ::uint32_t
    TableStruct_parameter_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::nodehub::ParameterValue, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::nodehub::ParameterValue, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::nodehub::ParameterValue, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::nodehub::ParameterValue, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::nodehub::ParameterValue, _impl_.value_),
        PROTOBUF_FIELD_OFFSET(::nodehub::ParameterValue, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::nodehub::ParameterValue)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::nodehub::_ParameterValue_default_instance_._instance,
};
const char descriptor_table_protodef_parameter_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017parameter.proto\022\007nodehub\"k\n\016ParameterV"
    "alue\022\021\n\007int_val\030\001 \001(\005H\000\022\023\n\tfloat_val\030\002 \001"
    "(\002H\000\022\022\n\010bool_val\030\003 \001(\010H\000\022\024\n\nstring_val\030\004"
    " \001(\tH\000B\007\n\005valueb\006proto3"
};
static ::absl::once_flag descriptor_table_parameter_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_parameter_2eproto = {
    false,
    false,
    143,
    descriptor_table_protodef_parameter_2eproto,
    "parameter.proto",
    &descriptor_table_parameter_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_parameter_2eproto::offsets,
    file_level_enum_descriptors_parameter_2eproto,
    file_level_service_descriptors_parameter_2eproto,
};
namespace nodehub {
// ===================================================================

class ParameterValue::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::nodehub::ParameterValue, _impl_._oneof_case_);
};

ParameterValue::ParameterValue(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParameterValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:nodehub.ParameterValue)
}
PROTOBUF_NDEBUG_INLINE ParameterValue::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::nodehub::ParameterValue& from_msg)
      : value_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

ParameterValue::ParameterValue(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ParameterValue& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ParameterValue_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ParameterValue* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (value_case()) {
    case VALUE_NOT_SET:
      break;
      case kIntVal:
        _impl_.value_.int_val_ = from._impl_.value_.int_val_;
        break;
      case kFloatVal:
        _impl_.value_.float_val_ = from._impl_.value_.float_val_;
        break;
      case kBoolVal:
        _impl_.value_.bool_val_ = from._impl_.value_.bool_val_;
        break;
      case kStringVal:
        new (&_impl_.value_.string_val_) decltype(_impl_.value_.string_val_){arena, from._impl_.value_.string_val_};
        break;
  }

  // @@protoc_insertion_point(copy_constructor:nodehub.ParameterValue)
}
PROTOBUF_NDEBUG_INLINE ParameterValue::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : value_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void ParameterValue::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ParameterValue::~ParameterValue() {
  // @@protoc_insertion_point(destructor:nodehub.ParameterValue)
  SharedDtor(*this);
}
inline void ParameterValue::SharedDtor(MessageLite& self) {
  ParameterValue& this_ = static_cast<ParameterValue&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_value()) {
    this_.clear_value();
  }
  this_._impl_.~Impl_();
}

void ParameterValue::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:nodehub.ParameterValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (value_case()) {
    case kIntVal: {
      // No need to clear
      break;
    }
    case kFloatVal: {
      // No need to clear
      break;
    }
    case kBoolVal: {
      // No need to clear
      break;
    }
    case kStringVal: {
      _impl_.value_.string_val_.Destroy();
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = VALUE_NOT_SET;
}


inline void* PROTOBUF_NONNULL ParameterValue::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ParameterValue(arena);
}
constexpr auto ParameterValue::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ParameterValue),
                                            alignof(ParameterValue));
}
constexpr auto ParameterValue::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ParameterValue_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ParameterValue::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ParameterValue>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ParameterValue::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ParameterValue>(), &ParameterValue::ByteSizeLong,
              &ParameterValue::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ParameterValue, _impl_._cached_size_),
          false,
      },
      &ParameterValue::kDescriptorMethods,
      &descriptor_table_parameter_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ParameterValue_class_data_ =
        ParameterValue::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ParameterValue::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ParameterValue_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ParameterValue_class_data_.tc_table);
  return ParameterValue_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 0, 41, 2>
ParameterValue::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ParameterValue,
                          _impl_._cached_size_),  // no hasbits
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ParameterValue_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::nodehub::ParameterValue>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 int_val = 1;
    {PROTOBUF_FIELD_OFFSET(ParameterValue, _impl_.value_.int_val_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kInt32)},
    // float float_val = 2;
    {PROTOBUF_FIELD_OFFSET(ParameterValue, _impl_.value_.float_val_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kFloat)},
    // bool bool_val = 3;
    {PROTOBUF_FIELD_OFFSET(ParameterValue, _impl_.value_.bool_val_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kBool)},
    // string string_val = 4;
    {PROTOBUF_FIELD_OFFSET(ParameterValue, _impl_.value_.string_val_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\0\0\0\12\0\0\0"
    "nodehub.ParameterValue"
    "string_val"
  }},
};
PROTOBUF_NOINLINE void ParameterValue::Clear() {
// @@protoc_insertion_point(message_clear_start:nodehub.ParameterValue)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_value();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ParameterValue::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ParameterValue& this_ = static_cast<const ParameterValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ParameterValue::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ParameterValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:nodehub.ParameterValue)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.value_case()) {
    case kIntVal: {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_int_val(), target);
      break;
    }
    case kFloatVal: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_float_val(), target);
      break;
    }
    case kBoolVal: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_bool_val(), target);
      break;
    }
    case kStringVal: {
      const ::std::string& _s = this_._internal_string_val();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "nodehub.ParameterValue.string_val");
      target = stream->WriteStringMaybeAliased(4, _s, target);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:nodehub.ParameterValue)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ParameterValue::ByteSizeLong(const MessageLite& base) {
  const ParameterValue& this_ = static_cast<const ParameterValue&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ParameterValue::ByteSizeLong() const {
  const ParameterValue& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:nodehub.ParameterValue)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.value_case()) {
    // int32 int_val = 1;
    case kIntVal: {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_int_val());
      break;
    }
    // float float_val = 2;
    case kFloatVal: {
      total_size += 5;
      break;
    }
    // bool bool_val = 3;
    case kBoolVal: {
      total_size += 2;
      break;
    }
    // string string_val = 4;
    case kStringVal: {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_string_val());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ParameterValue::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ParameterValue*>(&to_msg);
  auto& from = static_cast<const ParameterValue&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:nodehub.ParameterValue)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_value();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kIntVal: {
        _this->_impl_.value_.int_val_ = from._impl_.value_.int_val_;
        break;
      }
      case kFloatVal: {
        _this->_impl_.value_.float_val_ = from._impl_.value_.float_val_;
        break;
      }
      case kBoolVal: {
        _this->_impl_.value_.bool_val_ = from._impl_.value_.bool_val_;
        break;
      }
      case kStringVal: {
        if (oneof_needs_init) {
          _this->_impl_.value_.string_val_.InitDefault();
        }
        _this->_impl_.value_.string_val_.Set(from._internal_string_val(), arena);
        break;
      }
      case VALUE_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ParameterValue::CopyFrom(const ParameterValue& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:nodehub.ParameterValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ParameterValue::InternalSwap(ParameterValue* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata ParameterValue::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace nodehub
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_parameter_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
