// Command ids + label/bitmap resource ids for the own-ribbon toolbar (`OwnRibbonTab` / `COwnRibbonToolStrip`).
// Previously produced by uicc from Ribbon.xml; maintain by hand when adding or renumbering tools.

#pragma once

#define cmdTabHome 400 
#define cmdTabHome_LabelTitle_RESID 4001
#define cmdGroupQueue 401 
#define cmdGroupQueue_LabelTitle_RESID 4011
#define cmdGroupActions 402 
#define cmdGroupActions_LabelTitle_RESID 4021
#define cmdGroupSave 403 
#define cmdGroupSave_LabelTitle_RESID 4031
#define cmdGroupRun 411 
#define cmdGroupRun_LabelTitle_RESID 4111
#define cmdGroupBatch 412 
#define cmdGroupBatch_LabelTitle_RESID 4121
#define cmdGroupSession 413 
#define cmdGroupSession_LabelTitle_RESID 4131
#define IDC_CMD_SAVE_AS 357 
#define IDC_CMD_SAVE_AS_LabelTitle_RESID 3571
#define IDC_CMD_SAVE_AS_TooltipDescription_RESID 3572
#define IDC_CMD_SAVE_AS_SmallImages_RESID 3573
#define IDC_CMD_SAVE_AS_LargeImages_RESID 3574
#define IDC_CMD_ADD_FILES 302 
#define IDC_CMD_ADD_FILES_LabelTitle_RESID 3021
#define IDC_CMD_ADD_FILES_SmallImages_RESID 3023
#define IDC_CMD_ADD_FILES_LargeImages_RESID 3022
#define IDC_CMD_ADD_FOLDER 303 
#define IDC_CMD_ADD_FOLDER_LabelTitle_RESID 3031
#define IDC_CMD_ADD_FOLDER_SmallImages_RESID 3033
#define IDC_CMD_ADD_FOLDER_LargeImages_RESID 3032
#define IDC_CMD_CLEAR 301 
#define IDC_CMD_CLEAR_LabelTitle_RESID 3011
#define IDC_CMD_CLEAR_SmallImages_RESID 3013
#define IDC_CMD_CLEAR_LargeImages_RESID 3012
#define IDC_CMD_RESIZE 300 
#define IDC_CMD_RESIZE_LabelTitle_RESID 3001
#define IDC_CMD_RESIZE_SmallImages_RESID 3003
#define IDC_CMD_RESIZE_LargeImages_RESID 3002
#define IDC_CMD_COMPRESS 313 
#define IDC_CMD_COMPRESS_LabelTitle_RESID 3131
#define IDC_CMD_COMPRESS_SmallImages_RESID 3133
#define IDC_CMD_COMPRESS_LargeImages_RESID 3132
#define IDC_CMD_META 314 
#define IDC_CMD_META_LabelTitle_RESID 3141
#define IDC_CMD_META_SmallImages_RESID 3143
#define IDC_CMD_META_LargeImages_RESID 3142
#define IDC_CMD_TRANSFORM 315 
#define IDC_CMD_TRANSFORM_LabelTitle_RESID 3151
#define IDC_CMD_TRANSFORM_SmallImages_RESID 3153
#define IDC_CMD_TRANSFORM_LargeImages_RESID 3152
#define IDC_CMD_FIND 316 
#define IDC_CMD_FIND_LabelTitle_RESID 3161
#define IDC_CMD_FIND_SmallImages_RESID 3163
#define IDC_CMD_FIND_LargeImages_RESID 3162
#define IDC_CMD_DUPLICATES 324 
#define IDC_CMD_DUPLICATES_LabelTitle_RESID 3241
#define IDC_CMD_DUPLICATES_SmallImages_RESID 3243
#define IDC_CMD_DUPLICATES_LargeImages_RESID 3242
#define IDC_CMD_CHAT 317 
#define IDC_CMD_CHAT_LabelTitle_RESID 3171
#define IDC_CMD_CHAT_TooltipDescription_RESID 3172
#define IDC_CMD_CHAT_SmallImages_RESID 3174
#define IDC_CMD_CHAT_LargeImages_RESID 3173
#define IDC_CMD_RUN 312 
#define IDC_CMD_RUN_LabelTitle_RESID 3121
#define IDC_CMD_RUN_SmallImages_RESID 3123
#define IDC_CMD_RUN_LargeImages_RESID 3122
#define IDC_CMD_PAUSE 319 
#define IDC_CMD_PAUSE_LabelTitle_RESID 3191
#define IDC_CMD_PAUSE_TooltipDescription_RESID 3192
#define IDC_CMD_PAUSE_SmallImages_RESID 3193
#define IDC_CMD_PAUSE_LargeImages_RESID 3194
#define IDC_CMD_RESUME 320 
#define IDC_CMD_RESUME_LabelTitle_RESID 3201
#define IDC_CMD_RESUME_TooltipDescription_RESID 3202
#define IDC_CMD_RESUME_SmallImages_RESID 3203
#define IDC_CMD_RESUME_LargeImages_RESID 3204
#define IDC_CMD_CANCEL 321 
#define IDC_CMD_CANCEL_LabelTitle_RESID 3211
#define IDC_CMD_CANCEL_TooltipDescription_RESID 3212
#define IDC_CMD_CANCEL_SmallImages_RESID 3213
#define IDC_CMD_CANCEL_LargeImages_RESID 3214
#define IDC_CMD_SAVE_SESSION 322 
#define IDC_CMD_SAVE_SESSION_LabelTitle_RESID 3221
#define IDC_CMD_SAVE_SESSION_TooltipDescription_RESID 3222
#define IDC_CMD_SAVE_SESSION_SmallImages_RESID 3223
#define IDC_CMD_SAVE_SESSION_LargeImages_RESID 3224
#define IDC_CMD_LOAD_SESSION 323 
#define IDC_CMD_LOAD_SESSION_LabelTitle_RESID 3231
#define IDC_CMD_LOAD_SESSION_TooltipDescription_RESID 3232
#define IDC_CMD_LOAD_SESSION_SmallImages_RESID 3233
#define IDC_CMD_LOAD_SESSION_LargeImages_RESID 3234
#define IDC_CMD_EXIT 304 
#define IDC_CMD_EXIT_LabelTitle_RESID 3041
#define IDC_CMD_UPDATE_EXPLORER 365 
#define IDC_CMD_UPDATE_EXPLORER_LabelTitle_RESID 3651
#define IDC_CMD_UPDATE_EXPLORER_TooltipDescription_RESID 3652
#define IDC_CMD_UPDATE_EXPLORER_SmallImages_RESID 3653
#define IDC_CMD_UPDATE_EXPLORER_LargeImages_RESID 3654
#define IDC_CMD_UNREGISTER_EXPLORER 366 
#define IDC_CMD_UNREGISTER_EXPLORER_LabelTitle_RESID 3661
#define IDC_CMD_UNREGISTER_EXPLORER_TooltipDescription_RESID 3662
#define IDC_CMD_UNREGISTER_EXPLORER_SmallImages_RESID 3663
#define IDC_CMD_UNREGISTER_EXPLORER_LargeImages_RESID 3664
#define IDC_CMD_ABOUT 305 
#define IDC_CMD_ABOUT_LabelTitle_RESID 3051
#define cmdTabView 420 
#define cmdTabView_LabelTitle_RESID 4201
#define cmdGroupPanels 421 
#define cmdGroupPanels_LabelTitle_RESID 4211
#define cmdGroupReset 422 
#define cmdGroupReset_LabelTitle_RESID 4221
#define IDC_CMD_VIEW_QUEUE 350 
#define IDC_CMD_VIEW_QUEUE_LabelTitle_RESID 3501
#define IDC_CMD_VIEW_QUEUE_SmallImages_RESID 3502
#define IDC_CMD_VIEW_QUEUE_LargeImages_RESID 3503
#define IDC_CMD_VIEW_LOG 351 
#define IDC_CMD_VIEW_LOG_LabelTitle_RESID 3511
#define IDC_CMD_VIEW_LOG_SmallImages_RESID 3512
#define IDC_CMD_VIEW_LOG_LargeImages_RESID 3513
#define IDC_CMD_VIEW_SETTINGS 352 
#define IDC_CMD_VIEW_SETTINGS_LabelTitle_RESID 3521
#define IDC_CMD_VIEW_SETTINGS_SmallImages_RESID 3522
#define IDC_CMD_VIEW_SETTINGS_LargeImages_RESID 3523
#define IDC_CMD_VIEW_FILETREE 361 
#define IDC_CMD_VIEW_FILETREE_LabelTitle_RESID 3611
#define IDC_CMD_VIEW_FILETREE_SmallImages_RESID 3612
#define IDC_CMD_VIEW_FILETREE_LargeImages_RESID 3613
#define IDC_CMD_VIEW_FINDRESULTS 362 
#define IDC_CMD_VIEW_FINDRESULTS_LabelTitle_RESID 3621
#define IDC_CMD_VIEW_FINDRESULTS_SmallImages_RESID 3622
#define IDC_CMD_VIEW_FINDRESULTS_LargeImages_RESID 3623
#define IDC_CMD_VIEW_DUPLICATERESULTS 364 
#define IDC_CMD_VIEW_DUPLICATERESULTS_LabelTitle_RESID 3641
#define IDC_CMD_VIEW_DUPLICATERESULTS_SmallImages_RESID 3642
#define IDC_CMD_VIEW_DUPLICATERESULTS_LargeImages_RESID 3643
#define IDC_CMD_VIEW_CHAT 363 
#define IDC_CMD_VIEW_CHAT_LabelTitle_RESID 3631
#define IDC_CMD_VIEW_CHAT_SmallImages_RESID 3632
#define IDC_CMD_VIEW_CHAT_LargeImages_RESID 3633
#define IDC_CMD_RESET_LAYOUT 355 
#define IDC_CMD_RESET_LAYOUT_LabelTitle_RESID 3551
#define IDC_CMD_RESET_LAYOUT_SmallImages_RESID 3552
#define IDC_CMD_RESET_LAYOUT_LargeImages_RESID 3553
#define IDC_CMD_DEBUG_STATE 356 
#define IDC_CMD_DEBUG_STATE_LabelTitle_RESID 3561
#define IDC_CMD_DEBUG_STATE_SmallImages_RESID 3562
#define IDC_CMD_DEBUG_STATE_LargeImages_RESID 3563
#define IDC_CMD_APP_SETTINGS 370 
#define IDC_CMD_APP_SETTINGS_LabelTitle_RESID 3701
#define IDC_CMD_APP_SETTINGS_TooltipTitle_RESID 3702
#define IDC_CMD_APP_SETTINGS_TooltipDescription_RESID 3703
#define IDC_CMD_APP_SETTINGS_SmallImages_RESID 3704
#define IDC_CMD_APP_SETTINGS_LargeImages_RESID 3705
#define IDC_CMD_FILE_OPTIONS 371 
#define IDC_CMD_FILE_OPTIONS_LabelTitle_RESID 3711
#define IDC_CMD_FILE_OPTIONS_TooltipTitle_RESID 3712
#define IDC_CMD_FILE_OPTIONS_TooltipDescription_RESID 3713
#define IDC_CMD_FILE_OPTIONS_SmallImages_RESID 3714
#define IDC_CMD_FILE_OPTIONS_LargeImages_RESID 3715
/// Log dock tool strip — copy all (same 16×16 slot as ribbon small images).
#define IDC_LOG_PANEL_COPY_SmallImages_RESID 3724
#define cmdAppMenu 710 
#define IDC_RIBBONHELP 700 
#define IDC_QAT 701 
#define IDC_CUSTOMIZE_QAT 702 
