# -P script: copy MSVC *release* UCRT/VC++ DLLs from Microsoft.VC*.CRT next to pm-image (dist/).
# Not for Debug: *D.dll are not redistributable; use a Release (or RelWithDebInfo) build to ship.
# Pass: -DPM_DIST= -DPM_CL=path/to/cl.exe  -DPM_CONFIG=$<CONFIG>  -DPM_CMAKE_BUILD_TYPE= (Ninja single-config)
if(NOT DEFINED PM_DIST)
  message(FATAL_ERROR "copy_msvc_crt_to_dist: PM_DIST not set")
endif()
if(NOT DEFINED PM_CL)
  message(FATAL_ERROR "copy_msvc_crt_to_dist: PM_CL (path to cl.exe) not set")
endif()

set(_cfg "${PM_CONFIG}")
if("${_cfg}" STREQUAL "")
  set(_cfg "${PM_CMAKE_BUILD_TYPE}")
endif()
string(TOLOWER "${_cfg}" _clower)
if(_clower STREQUAL "debug")
  message(STATUS "MSVC CRT → dist: skipped (Debug; ship a Release build or install VS debug CRT locally)")
  return()
endif()

get_filename_component(_cl "${PM_CL}" ABSOLUTE)
if(NOT EXISTS "${_cl}")
  message(WARNING "MSVC CRT: cl not found: ${_cl}")
  return()
endif()
get_filename_component(_1 "${_cl}" DIRECTORY)
get_filename_component(_2 "${_1}" DIRECTORY)
get_filename_component(_3 "${_2}" DIRECTORY)
get_filename_component(_verdir "${_3}" DIRECTORY)
get_filename_component(_vnum "${_verdir}" NAME)
get_filename_component(_4 "${_verdir}" DIRECTORY)
get_filename_component(_5 "${_4}" DIRECTORY)
get_filename_component(_vcroot "${_5}" DIRECTORY)
set(_g "${_vcroot}/Redist/MSVC/${_vnum}/x64/Microsoft.VC*.CRT")
file(GLOB _crt_glob "${_g}")
if(NOT _crt_glob)
  message(WARNING "MSVC CRT: no redist at ${_g}")
  return()
endif()
list(GET _crt_glob 0 _crt)
file(GLOB _dlls "${_crt}/*.dll")
if(NOT _dlls)
  message(WARNING "MSVC CRT: no DLLs in ${_crt}")
  return()
endif()
file(MAKE_DIRECTORY "${PM_DIST}")
set(_n 0)
foreach(_d IN LISTS _dlls)
  get_filename_component(_b "${_d}" NAME)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_d}" "${PM_DIST}/${_b}"
    RESULT_VARIABLE _e
  )
  if(_e EQUAL 0)
    math(EXPR _n "${_n} + 1")
  endif()
endforeach()
message(STATUS "MSVC CRT → dist: copied ${_n} DLLs to ${PM_DIST}")
