if(NOT UNIX OR APPLE)
  return()
endif()

set(CPACK_GENERATOR "TGZ")
set(CPACK_PACKAGE_NAME "${PM_APP_ID_SLUG}")
set(CPACK_PACKAGE_VENDOR "${PM_BRAND_VENDOR}")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/dist")
set(CPACK_PACKAGING_INSTALL_PREFIX "")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY ON)
set(CPACK_VERBATIM_VARIABLES YES)

string(TOLOWER "${CMAKE_SYSTEM_NAME}" _PM_CPACK_SYSTEM_NAME)
set(_PM_CPACK_PROCESSOR "${CMAKE_SYSTEM_PROCESSOR}")
if(_PM_CPACK_PROCESSOR STREQUAL "AMD64")
  set(_PM_CPACK_PROCESSOR "x86_64")
endif()

set(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}-${_PM_CPACK_SYSTEM_NAME}-${_PM_CPACK_PROCESSOR}")

include(CPack)
